### ISSUE TITLE
seed for repeatability

### ISSUE THREAD

**Issue by yoachim** [ufeindt/simsurvey#29]
It would be nice if the random number generator seed could be set (maybe as a kwarg on `get_transient_generator`) so simulated populations would be easily repeatable.

**Comment by ufeindt** [comment]
The email notification for this issue got lost among all the other github mails, so apologies for the late response.

Yes, this would be a nice feature indeed. I will add kwargs for it the `TransientGenerator` and `SimulSurvey` objects in the next version.

In the meantime, note that all random numbers are generated using numpy, so the seed can be set globally using `np.random.seed`.

**Comment by ufeindt** [comment]
Options to set the seed have been included in the latest relases.
